import { useState } from "react";
import styles from "./ReportsPage.module.css";

const reportData = [
  {
    id: "RPT-001",
    type: "Revenue",
    period: "March 2026",
    generatedBy: "Admin",
    date: "12/01/2026",
    status: "Completed",
  },
  {
    id: "RPT-002",
    type: "Payments",
    period: "March 2026",
    generatedBy: "Admin",
    date: "02/02/2026",
    status: "Completed",
  },
  {
    id: "RPT-003",
    type: "Outstanding",
    period: "March 2026",
    generatedBy: "Provider",
    date: "04/02/2026",
    status: "Pending",
  },
];

function ReportsPage() {
  const [search, setSearch] = useState("");
  const [reportType, setReportType] = useState("");
  const [status, setStatus] = useState("");
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");

  const parseDate = (dateString: string) => {
    const [month, day, year] = dateString.split("/");
    return new Date(Number(year), Number(month) - 1, Number(day));
  };

  const filteredReports = reportData.filter((report) => {
    const matchesSearch =
      !search ||
      report.id.toLowerCase().includes(search.toLowerCase()) ||
      report.type.toLowerCase().includes(search.toLowerCase());

    const matchesType =
      !reportType || report.type.toLowerCase() === reportType.toLowerCase();

    const matchesStatus =
      !status || report.status.toLowerCase() === status.toLowerCase();

    //Date filtering
    const reportDate = parseDate(report.date);

    const matchesFromDate = !fromDate || reportDate >= new Date(fromDate);

    const matchesToDate = !toDate || reportDate <= new Date(toDate);

    return (
      matchesSearch &&
      matchesType &&
      matchesStatus &&
      matchesFromDate &&
      matchesToDate
    );
  });

  const handleClear = () => {
    setSearch("");
    setReportType("");
    setStatus("");
    setFromDate("");
    setToDate("");
  };

  return (
    <div className={styles.container}>
      {/* Header */}
      <div className={styles.header}>
        <h2>Reports</h2>

        <div className={styles.headerActions}>
          <button className={styles.exportButton}>Export CSV</button>
          <button className={styles.exportButton}>Export PDF</button>
        </div>
      </div>

      {/* Summary Cards */}
      <div className={styles.summaryGrid}>
        <div className={styles.card}>
          <h4>Total Revenue</h4>
          <p>$45,320</p>
        </div>

        <div className={styles.card}>
          <h4>Total Payments</h4>
          <p>$38,900</p>
        </div>

        <div className={styles.card}>
          <h4>Outstanding Balance</h4>
          <p>$6,420</p>
        </div>

        <div className={styles.card}>
          <h4>Claims Submitted</h4>
          <p>128</p>
        </div>
      </div>

      {/* Filters */}
      <div className={styles.filterContainer}>
        <input
          type="text"
          placeholder="Search Report ID or Type..."
          className={styles.searchInput}
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />

        <select
          className={styles.select}
          value={reportType}
          onChange={(e) => setReportType(e.target.value)}
        >
          <option value="">Report Type</option>
          <option value="Revenue">Revenue</option>
          <option value="Payments">Payments</option>
          <option value="Outstanding">Outstanding</option>
          <option value="Claims">Claims</option>
        </select>

        <label className={styles.dateLabel}>Start Date</label>
        <input
          type="date"
          className={styles.dateInput}
          value={fromDate}
          onChange={(e) => setFromDate(e.target.value)}
        />

        <label className={styles.dateLabel}>End Date</label>
        <input
          type="date"
          className={styles.dateInput}
          value={toDate}
          onChange={(e) => setToDate(e.target.value)}
        />

        <select
          className={styles.select}
          value={status}
          onChange={(e) => setStatus(e.target.value)}
        >
          <option value="">Status</option>
          <option value="Completed">Completed</option>
          <option value="Pending">Pending</option>
          <option value="Failed">Failed</option>
        </select>

        <button className={styles.clearButton} onClick={handleClear}>
          Clear Filters
        </button>
      </div>

      {/* Table */}
      <div className={styles.tableContainer}>
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Report ID</th>
              <th>Report Type</th>
              <th>Period</th>
              <th>Generated By</th>
              <th>Date</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            {filteredReports.map((report) => (
              <tr key={report.id}>
                <td>{report.id}</td>
                <td>{report.type}</td>
                <td>{report.period}</td>
                <td>{report.generatedBy}</td>
                <td>{report.date}</td>

                <td>
                  <span
                    className={`${styles.status} ${
                      styles[report.status.toLowerCase()]
                    }`}
                  >
                    {report.status}
                  </span>
                </td>

                <td>
                  <div className={styles.actions}>
                    <button className={styles.actionButton}>View</button>

                    <button className={styles.actionButton}>Download</button>

                    <button className={styles.actionButton}>Share</button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default ReportsPage;
